from . import l10n_br
from . import br_base
from . import res_company
from . import res_country
from . import res_partner
from . import res_bank
from . import res_users
from . import br_zip
from . import res_company
from . import res_partner
from . import res_bank
